services:
  db:
    image: postgres:16-alpine
    restart: 'on-failure'
    container_name: 'db'
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: manager
      POSTGRES_DB: db_management
    volumes:
      - './db-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    secrets:
      - db_password
secrets:
  db_password:
    file: db_password.txt
